// Import the old Format-site content from scripts/format-manifest.json
// (generated by generate-format-manifest.py — review it before running this).
//
// Idempotent: GCS objects are skipped when present, Media rows upsert by key,
// publications/press upsert by slug, and each item's gallery is rebuilt
// (delete + recreate) so re-runs converge. Sources: local ./media originals
// preferred, signed format.creatorcdn.com URL as fallback. Images are
// EXIF-rotated, downscaled to ≤2400px and re-encoded as JPEG via sharp.
//
// Also: re-links the polynesia cover (lost in the Jun-3 migration), deletes
// the test rows, and reassigns sortOrder (year desc, title asc) across both
// publications and press.
//
// Run: npm run import:format
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import dotenv from "dotenv";
import sharp from "sharp";
import DOMPurify from "isomorphic-dompurify";
import { Storage } from "@google-cloud/storage";
import { PrismaNeon } from "@prisma/adapter-neon";
import { PrismaClient } from "../src/generated/prisma/client";

dotenv.config({ path: ".env.local" });
dotenv.config();

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL must be set.");
const db = new PrismaClient({ adapter: new PrismaNeon({ connectionString }) });

const storage = new Storage({
  projectId: process.env.GCS_PROJECT_ID,
  credentials: {
    client_email: process.env.GCS_CLIENT_EMAIL,
    private_key: process.env.GCS_PRIVATE_KEY?.replace(/\\n/g, "\n"),
  },
});
const bucket = storage.bucket(process.env.GCS_BUCKET_NAME!);
const publicUrl = (key: string) => `/media/${key}`;

const ROOT = join(import.meta.dirname, "..");
const MAX_DIM = 2400;

// Mirror src/lib/sanitize.ts (which is `server-only` and can't load under tsx).
const sanitize = (html: string) =>
  DOMPurify.sanitize(html, {
    ALLOWED_TAGS: ["p","br","strong","b","em","i","s","u","code","pre","h1","h2","h3","h4","ul","ol","li","blockquote","a","img","figure","figcaption"],
    ALLOWED_ATTR: ["href","target","rel","src","alt","title","width","height"],
    ALLOWED_URI_REGEXP: /^(?:https?:|mailto:|tel:|#|\/)/i,
  });

type GalleryEntry = { file: string; local: string | null; cdn: string | null; title: string | null; caption: string | null };
type BodyImage = { file: string; local: string | null; cdn: string | null };
type Cover = { local: string | null; cdn: string | null; file: string };
type PubItem = {
  action: "create" | "enrich"; slug: string; sortOrder: number;
  cover: Cover; gallery: GalleryEntry[]; bodyImages?: BodyImage[];
  title?: string; year?: number; kind?: string; region?: string; publisher?: string; body?: string;
  galleryLayout?: "Grid" | "List";
};
type PressItem = {
  action: "create"; slug: string; sortOrder: number; outlet: string; title: string;
  subtitle: string; year: number; cover: Cover; gallery: GalleryEntry[]; bodyImages?: BodyImage[];
  body?: string; galleryLayout?: "Grid" | "List";
};

const manifest: { publications: PubItem[]; press: PressItem[] } = JSON.parse(
  readFileSync(join(ROOT, "scripts", "format-manifest.json"), "utf-8"),
);

const slugifyName = (s: string) =>
  s.toLowerCase().replace(/\.[a-z0-9]+$/i, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);

async function sourceBytes(e: { local: string | null; cdn: string | null }, what: string): Promise<Buffer> {
  if (e.local) {
    const p = join(ROOT, e.local);
    if (existsSync(p)) return readFileSync(p);
  }
  if (e.cdn) {
    const res = await fetch(e.cdn);
    if (!res.ok) throw new Error(`CDN fetch ${res.status} for ${what}`);
    return Buffer.from(await res.arrayBuffer());
  }
  throw new Error(`no source for ${what}`);
}

/** Process → upload (if missing) → Media upsert. Returns media id. */
async function ensureImage(src: { local: string | null; cdn: string | null }, key: string, alt: string | null) {
  const raw = await sourceBytes(src, key);
  const img = sharp(raw, { failOn: "none" }).rotate();
  const meta = await img.metadata();
  const needsResize = (meta.width ?? 0) > MAX_DIM || (meta.height ?? 0) > MAX_DIM;
  const out = await img
    .resize({ width: MAX_DIM, height: MAX_DIM, fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: 82, mozjpeg: true })
    .toBuffer({ resolveWithObject: true });

  const file = bucket.file(key);
  const [exists] = await file.exists();
  if (!exists) {
    await file.save(out.data, { contentType: "image/jpeg", resumable: false });
    console.log(`    ↑ ${key} (${(out.info.size / 1024).toFixed(0)} KB${needsResize ? ", downscaled" : ""})`);
  }
  const media = await db.media.upsert({
    where: { key },
    update: { url: publicUrl(key), mimeType: "image/jpeg", bytes: out.info.size, width: out.info.width, height: out.info.height, alt },
    create: { key, url: publicUrl(key), mimeType: "image/jpeg", bytes: out.info.size, width: out.info.width, height: out.info.height, alt },
  });
  return media.id;
}

/**
 * Resolve a body: upload its inline images (interleaved articles — the old
 * site shows photos between paragraphs) and swap the generator's
 * `<img data-import-file="...">` placeholders for final /media URLs.
 */
async function resolveBody(body: string | undefined, bodyImages: BodyImage[] | undefined, prefix: string) {
  let html = body ?? "";
  for (let i = 0; i < (bodyImages?.length ?? 0); i++) {
    const e = bodyImages![i];
    const key = `${prefix}/body/${String(i + 1).padStart(2, "0")}-${slugifyName(e.file)}.jpg`;
    await ensureImage(e, key, null);
    html = html.split(`<img data-import-file="${e.file}">`).join(`<img src="${publicUrl(key)}" alt="" />`);
  }
  return sanitize(html);
}

/** Drop gallery media left over from a previous run when images moved inline. */
async function dropStaleGalleryMedia(prefix: string) {
  const stale = await db.media.deleteMany({ where: { key: { startsWith: `${prefix}/gallery/` } } });
  if (stale.count) {
    try { await bucket.deleteFiles({ prefix: `${prefix}/gallery/` }); } catch { /* best-effort */ }
    console.log(`    − removed ${stale.count} stale gallery media`);
  }
}

async function buildGallery(prefix: string, entries: GalleryEntry[]) {
  const rows: { mediaId: string; title: string | null; caption: string | null; sortOrder: number }[] = [];
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i];
    const key = `${prefix}/gallery/${String(i + 1).padStart(2, "0")}-${slugifyName(e.file)}.jpg`;
    const mediaId = await ensureImage(e, key, e.title);
    rows.push({ mediaId, title: e.title, caption: e.caption, sortOrder: i });
  }
  return rows;
}

async function main() {
  // ── Publications ────────────────────────────────────────────────────────
  for (const item of manifest.publications) {
    console.log(`▸ publication ${item.slug} (${item.action})`);
    const prefix = `publications/${item.slug}`;
    const coverId = await ensureImage(item.cover, `${prefix}/cover.jpg`, item.title ?? item.slug);
    const gallery = await buildGallery(prefix, item.gallery);
    const body = item.body || item.bodyImages?.length
      ? await resolveBody(item.body, item.bodyImages, prefix)
      : null;

    const common = {
      coverImageId: coverId,
      ...(item.title ? { title: item.title } : {}),
      ...(body !== null ? { body } : {}),
      ...(item.galleryLayout ? { galleryLayout: item.galleryLayout } : {}),
    };
    let pubId: string;
    if (item.action === "create") {
      const created = await db.publication.upsert({
        where: { slug: item.slug },
        update: {
          ...common,
          year: item.year!, kind: item.kind as never, region: item.region as never,
          publisher: item.publisher ?? null,
        },
        create: {
          slug: item.slug, title: item.title!, year: item.year!,
          kind: item.kind as never, region: item.region as never,
          publisher: item.publisher ?? null, body: body ?? "",
          coverImageId: coverId, published: true,
        },
      });
      pubId = created.id;
    } else {
      const updated = await db.publication.update({ where: { slug: item.slug }, data: common });
      pubId = updated.id;
    }
    await db.galleryImage.deleteMany({ where: { publicationId: pubId } });
    for (const g of gallery) await db.galleryImage.create({ data: { ...g, publicationId: pubId } });
    if (item.bodyImages?.length && gallery.length === 0) await dropStaleGalleryMedia(prefix);
    console.log(`    ✓ gallery ${gallery.length}, cover linked`);
  }

  // ── Press ───────────────────────────────────────────────────────────────
  for (const item of manifest.press) {
    console.log(`▸ press ${item.slug}`);
    const prefix = `press/${item.slug}`;
    const coverId = await ensureImage(item.cover, `${prefix}/cover.jpg`, item.title);
    const gallery = await buildGallery(prefix, item.gallery);
    const data = {
      outlet: item.outlet, title: item.title, subtitle: item.subtitle, year: item.year,
      body: await resolveBody(item.body, item.bodyImages, prefix),
      coverImageId: coverId, published: true,
      ...(item.galleryLayout ? { galleryLayout: item.galleryLayout } : {}),
    };
    const row = await db.pressItem.upsert({
      where: { slug: item.slug },
      update: data,
      create: { slug: item.slug, ...data },
    });
    await db.galleryImage.deleteMany({ where: { pressItemId: row.id } });
    for (const g of gallery) await db.galleryImage.create({ data: { ...g, pressItemId: row.id } });
    if (item.bodyImages?.length && gallery.length === 0) await dropStaleGalleryMedia(prefix);
    console.log(`    ✓ gallery ${gallery.length}, cover linked`);
  }

  // ── Fix-ups ─────────────────────────────────────────────────────────────
  // polynesia cover (link lost in the Jun-3 migration; object already in GCS)
  const polyCover = await db.media.findUnique({ where: { key: "publications/polynesia/cover.jpeg" } });
  if (polyCover) {
    await db.publication.updateMany({ where: { slug: "polynesia" }, data: { coverImageId: polyCover.id } });
    console.log("▸ re-linked polynesia cover");
  }
  // test rows
  const delPub = await db.publication.deleteMany({ where: { slug: "test-publication" } });
  const delPress = await db.pressItem.deleteMany({ where: { outlet: "test-outlet" } });
  if (delPub.count || delPress.count) console.log(`▸ removed test rows (pub:${delPub.count}, press:${delPress.count})`);

  // ── Global ordering: year desc, title asc ───────────────────────────────
  const pubs = await db.publication.findMany({ select: { id: true, year: true, title: true } });
  pubs.sort((a, b) => b.year - a.year || a.title.localeCompare(b.title));
  await db.$transaction(pubs.map((p, i) => db.publication.update({ where: { id: p.id }, data: { sortOrder: i } })));
  const press = await db.pressItem.findMany({ select: { id: true, year: true, title: true } });
  press.sort((a, b) => b.year - a.year || a.title.localeCompare(b.title));
  await db.$transaction(press.map((p, i) => db.pressItem.update({ where: { id: p.id }, data: { sortOrder: i } })));
  console.log(`▸ reordered ${pubs.length} publications, ${press.length} press items (year desc)`);
}

main()
  .then(async () => {
    await db.$disconnect();
    console.log("✅ Format import complete.");
  })
  .catch(async (err) => {
    console.error("❌ Import failed:", err);
    await db.$disconnect();
    process.exit(1);
  });
